#Sensors
FLAME_SENSOR=22
INFRARRED_RECEIVER_SENSOR=0
INFRARRED_EMITTER_SENSOR=0
RGB_LCD_SENSOR=2
TEMP_HUM_SENSOR=5
TOUCH_SENSOR_1x1=16
TOUCH_SENSOR_1x2=18
TOUCH_SENSOR_2x1=24
TOUCH_SENSOR_2x2=26

#Influx
INFLUXDB_TOKEN = "6QCOt656axj-tWsEeTmZZ_URFB0ASrib1NZ0uGpqjuw-1ygd4xUeZzHhYHEkvt6y-wuERAY9ZYHFBsLCVHyw3Q=="

#User
USERNAME= "jorge.ibai@gmail.com"